### ISSUE TITLE
marker-width: 1 on Heatmap types results in rendered pixels

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/torque#115]
If you change the marker-width: 1, then nothing is ever rendered
I'm wondering if that is expected... or if there should be something

**Comment by fdansv** [comment]
If you look very closely and set the opacity to 1, you can see there is stuff being rendered, it's just very hard to see. Rememeber that when we add a heatmap point size 1px, we're not adding a point per se, but this marker:

![](http://s3.amazonaws.com/com.cartodb.assets.static/alphamarker.png)

Scaled to 1x1 dimensions. So you won't really start to see them until there is some heavy overlapping. We can of course modify the renderer so that size one is equivalent to size one in opaque pixels, but I'm personally not a fan of that.

**Comment by andrewxhill** [comment]
perfect... easy to miss i guess

On Wed, Feb 4, 2015 at 9:28 AM, Francisco Dans <notifications@github.com>
wrote:

> If you look very closely and set the opacity to 1, you can see there is
> stuff being rendered, it's just very hard to see. Rememeber that when we
> add a heatmap point size 1px, we're not adding a point per se, but this
> marker:
>
>
> <https://camo.githubusercontent.com/0ed7376c7f89b9cc8b26ce9071e8610c97913182/687474703a2f2f73332e616d617a6f6e6177732e636f6d2f636f6d2e636172746f64622e6173736574732e7374617469632f616c7068616d61726b65722e706e67>
>
> Scaled to 1x1 dimensions. So you won't really start to see them until
> there is some heavy overlapping. We can of course modify the renderer so
> that size one is equivalent to size one in opaque pixels, but I'm
> personally not a fan of that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/torque/issues/115#issuecomment-72862525>.
>



-- 

andrewxhill <http://twitter.com/andrewxhill>
http://cartodb.com
