### ISSUE TITLE
Additional compositing operations

### ISSUE THREAD

**Issue by makella** [CartoDB/torque#253]
Hello,
I'm wondering if we can add two additional compositing operations. As pointed out in [this issue](https://github.com/CartoDB/cartod1b.js/issues/84), I understand that this is different from standard CartoCSS, so if isn't possible, its ok and I'll find workarounds but thought I should ask! 

The two that I would like to request are `soft-light` and/or `overlay`. Specifically, to work with many overlapping points in the Big Data Dashboard. Both, to different degrees, help us see underlying points on both Dark Matter and Positron adding a little mixing effect, bringing out smaller points that are otherwise not as  well defined.

Here is an example of overlapping points and the effects of both comp-ops on Positron and Dark Matter

![screen shot 2016-02-08 at 9 30 13 am](https://cloud.githubusercontent.com/assets/1566273/12891888/d6a1c854-ce46-11e5-8c5b-710b4455149f.png)

Thanks and please let me know if there is any other information needed.
mamata

**Comment by fdansv** [comment]
OK I see the problem here. We're basically taking all supported blending modes from CartoCSS and mapping them to their canvas counterparts. Problem here is that it seems that [only the most common ones have been declared](https://github.com/CartoDB/torque/blob/master/lib/torque/renderer/point.js#L22-L35). Fixing that now.

**Comment by makella** [comment]
awesome, thanks @fdansv!
mamata

**Comment by fdansv** [comment]
This was fixed in #254
